### ISSUE TITLE
Amazon Linux AMI 2015.09

### ISSUE THREAD

**Issue by dilab** [profburial/wkhtmltopdf-binaries#1]
Hi 

Thanks for the awesome binaries. 

So which distro I should use for Amazon Linux AMI 2015.09?

**Comment by dilab** [comment]
In  version 0.12.3 there are static binaries again, not special for any distribution. (http://wkhtmltopdf.org/downloads.html. )

Do you plan to include that?

**Comment by profburial** [comment]
You're welcome! I believe AL is based on Centos/Red Hat, so I would try the Centos 6 binaries and see if those work. 

I actually don't use these binaries for the project they were originally intended for anymore, so I haven't had a need to update in awhile. I might be able to include 0.12.3 since you requested it when I have a little free time. You are also more than welcome to send a PR with that update (and it would be appreciated). 

Good luck!

**Comment by dilab** [comment]
Ok. 
I ended up with using https://github.com/h4cc/wkhtmltopdf-amd64. 
It worked out great.
